apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolioapp
        image: ghcr.io/abila98/portfolioapp:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: github
