---
- name: Install Docker and run Docker image as a service
  hosts: all
  #become: true

  vars:
    docker_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65363333333838653631616334333832353461653235383237626636663965373538393735303930
      6565326464306330363438333832383933326336636131360a643533343033653032356637303438
      38333332623932636236616566626539303138646136383164363161326164393239376463313130
      6631393830336663650a643334613436303366343839613935626332646537633134383434346230
      38363934643534396134613633303138623031396330373832663835383963323235386335363237
      3531656662643136653537653732643863346566636638663934

  tasks:
    - name: Update Yum
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Ensure unzip is installed
      yum:
        name: unzip
        state: present
      become: yes

    - name: Ensure jq is installed
      yum:
        name: jq
        state: present
      become: yes


    - name: Install Docker
      command: sudo yum install docker -y
      become: yes

    - name: Download Docker Compose
      command: "sudo curl -L 'https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64' -o /usr/bin/docker-compose"

    - name: Make Docker Compose executable
      command: "sudo chmod +x /usr/bin/docker-compose"

    - name: Download AWS CLI
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Unzip AWS CLI package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install"
      args:
        creates: "/usr/local/bin/aws"

    - name: Add ec2-user to the Docker group
      become: yes
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker registry
      become: true
      docker_login:
        registry_url: "ghcr.io/abila98"
        username: "abila98"
        password: "{{ docker_password }}"

    - name: Create a folder
      file:
        path: /home/ec2-user/portfolio
        state: directory
        mode: 0755  

    - name: Copy a folder
      copy:
        src: ./extra/
        dest: /home/ec2-user/portfolio

    - name: Change ownership
      become: true
      file:
        path: /home/ec2-user/portfolio  
        state: directory
        owner: ec2-user
        group: docker
        mode: 0755

    - name: Change mode of shell scripts
      become: true
      file:
        path: "{{ item }}"
        mode: u+x
      loop:
        - /home/ec2-user/portfolio/secret.sh
        - /home/ec2-user/portfolio/service.sh

    - name: Run shell script with shell module
      become: true
      shell: /home/ec2-user/portfolio/service.sh

    - name: Reload systemd daemon
      become: true
      command: systemctl daemon-reload
    
    - name: Enable the service
      become: true
      systemd:
        name: portfolio
        enabled: yes

