---
- name: Install Docker and run Docker image as a service
  hosts: all
  #become: true

  vars:
    docker_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30373731323461666361333837323539303332663235623137353062333265373566646136383863
          3566616465373764613939326337323163396161363830300a363732643363396135383039366438
          65643134353962663836613030633662613935623839613932316133666161393434623436313939
          3362653534356266360a623436303936633532626630656564666231666234323631323663353264
          31363632356565316332653661623634333534623137333135373938393431363330313561383734
          6236613161363239613562353235626132653131383362643833

  tasks:
    - name: Update Yum
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Ensure unzip is installed
      yum:
        name: unzip
        state: present
      become: yes

    - name: Ensure jq is installed
      yum:
        name: jq
        state: present
      become: yes


    - name: Install Docker
      command: sudo yum install docker -y
      become: yes

    - name: Download Docker Compose
      command: "sudo curl -L 'https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64' -o /usr/bin/docker-compose"

    - name: Make Docker Compose executable
      command: "sudo chmod +x /usr/bin/docker-compose"

    - name: Download AWS CLI
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'
      become: yes

    - name: Unzip AWS CLI package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp/"
        remote_src: yes
      become: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install"
      args:
        creates: "/usr/local/bin/aws"
      become: yes

    - name: Add ec2-user to the Docker group
      become: yes
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker registry
      become: true
      docker_login:
        registry_url: "ghcr.io/abila98"
        username: "abila98"
        password: "{{ docker_password }}"

    - name: Create a folder
      file:
        path: /home/ec2-user/portfolio
        state: directory
        mode: 0755  

    - name: Copy a folder
      copy:
        src: ./extra/
        dest: /home/ec2-user/portfolio

    - name: Change ownership
      become: true
      file:
        path: /home/ec2-user/portfolio  
        state: directory
        owner: ec2-user
        group: docker
        mode: 0755

    - name: Change mode of shell scripts
      become: true
      file:
        path: "{{ item }}"
        mode: u+x
      loop:
        - /home/ec2-user/portfolio/secret.sh
        - /home/ec2-user/portfolio/service.sh

    - name: Run shell script with shell module
      become: true
      shell: /home/ec2-user/portfolio/service.sh

    - name: Reload systemd daemon
      become: true
      command: systemctl daemon-reload
    
    - name: Enable the service
      become: true
      systemd:
        name: portfolio
        enabled: yes

