apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolioapp
        image: ghcr.io/abila98/portfolioapp:latest
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: MYSQL_ROOT_PASSWORD
            - name: smtpHost
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: smtpHost
            - name: smtpUsername
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: smtpUsername
            - name: smtpPassword
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: smtpPassword
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: dbpassword        
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: github
