apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  smtpHost: ZW1haWwtc210cC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbQ==
  smtpUsername: QUtJQTZPRFU2V0lSUUhXVlQ0TUo=
  smtpPassword: QkxCM1lCblE0a2pEdEl2Zm92UkhvMVFZYzBEL2ZONVRhZytONmRCT1NoMXg=
  dbpassword: bXlwYXNzd29yZA==
