apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: portfolioapp
        image: ghcr.io/abila98/portfolioapp:latest
        env:
            - name: smtpHost
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: smtpHost
            - name: smtpUsername
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: smtpUsername
            - name: smtpPassword
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: smtpPassword
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: dbpassword        
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
        # Define Liveness Probe
        livenessProbe:
          httpGet:
            path: /portfolio/index.html
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        # Define Readiness Probe
        readinessProbe:
          httpGet:
            path: /portfolio/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
        - name: github
