apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql/
            - name: mysql-init-sql
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-init-sql
          configMap:
            name: mysql-init-sql
            items:
              - key: init.sql
                path: init.sql

        - name: mysql-data
          hostPath:
            path: /tmp/sql

