name: Packer Build on Tag

on:
  push:
    branches:
      - 'release/*'

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIAW775JRWDIKCYKVW6  # Set credentials within the job
      AWS_SECRET_ACCESS_KEY: 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

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          
      - name: Extract version from branch name
        id: extract-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/heads/release/}"
      
      - name: Decrypt vault password file
        env:
          VAULT_PASSWORD_FILE: ${{ secrets.VAULT_PASSWORD_FILE }}
        run: |
          echo "$VAULT_PASSWORD_FILE" | base64 --decode > vault_password_file
          cat vault_password_file  # Debugging step to verify the contents

      - name: Run Packer Build
        run: |
          ssh -oHostKeyAlgorithms=+ssh-dss -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes packer build -var 'tag_version=${{ steps.extract-version.outputs.version }}' -var-file vault_password_file ami/ami.json       
        env:
          AWS_ACCESS_KEY_ID: AKIAW775JRWDIKCYKVW6  # Set credentials within the job
          AWS_SECRET_ACCESS_KEY: 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
