name: Packer Build on Tag

on:
  push:
    branches:
      - 'release/*' # Trigger workflow on tags that start with 'v'

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          
      - name: Extract version from branch name
        id: extract-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/heads/release/}"
      
      - name: Decrypt vault password file
        env:
          VAULT_PASSWORD_FILE: ${{ secrets.VAULT_PASSWORD_FILE }}
        run: echo "$VAULT_PASSWORD_FILE" | base64 --decode > vault_password_file
      - name: Start SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_AGENT_PID" > $RUNNER_TEMP/ssh-agent.pid  # Store PID for later cleanup
          

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    
      # - name: Set Packer environment variables
      #   run: |
      #     echo "PACKER_SSH_KEY=$(secrets.SSH_KEY)" >> $GITHUB_ENV
      #     echo "AWS_ACCESS_KEY_ID=$(secrets.AWS_ACCESS_KEY_ID)" >> $GITHUB_ENV
      #     echo "AWS_SECRET_ACCESS_KEY=$(secrets.AWS_SECRET_ACCESS_KEY)" >> $GITHUB_ENV
          

      - name: Run Packer Build
        run: |
          packer build -var 'tag_version=${{ steps.extract-version.outputs.version }}' ami/ami.json
        env:
          AWS_ACCESS_KEY_ID: AKIAW775JRWDIKCYKVW6  # Set credentials within the job
          AWS_SECRET_ACCESS_KEY: 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
          SSH_OPTIONS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes"



