name: Packer AMI build

on:
  push:
    branches:
      - 'release/*'

jobs:

  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          
      - name: Extract version from branch name
        id: extract-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/heads/release/}"
      
      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          
      - name: Setup Vault Password file
        run: |
          echo "${{ secrets.VAULT_PASSWORD_FILE }}" >> vault_password_file
       
      - name: Packer init
        run: |
          packer init ami/ami.pkr.hcl

      - name: Run Packer Build
        run: |
          packer build -var 'tag_version=${{ steps.extract-version.outputs.version }}' ami/ami.pkr.hcl

