name: Packer Build on Tag

on:
  push:
    branches:
      - 'release/*' # Trigger workflow on tags that start with 'v'

jobs:
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          
      - name: Extract version from branch name
        id: extract-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/heads/release/}"
      
      - name: Decrypt vault password file
        env:
          VAULT_PASSWORD_FILE: ${{ secrets.VAULT_PASSWORD_FILE }}
        run: echo "$VAULT_PASSWORD_FILE" | base64 --decode > vault_password_file

      - name: Run Packer Build
        run: |
          packer build -var 'tag_version=${{ steps.extract-version.outputs.version }}' ami/ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set credentials within the job
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
