name: Terraform Destroy Infra

on:
  schedule:
    - cron: '0 17 * * *'  # Run at 5 PM UTC (adjusted for IST)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
          
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2  # Adjust this to match your Terraform version
        
    - name: Set up AWS credentials
      run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          
    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch'
      run: terraform destroy --auto-approve -input=false
      working-directory: terraform/
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_region: "us-west-1"  # Adjust this to match your desired region
